Feature/SDK-1391 prepare Mopub adapter for Header Bidding
appodeal/BidMachine-Android-mopub-adapter pull request #2
Opened 2019-08-05 12:11 UTC by NikitaCherep

2019-08-08 12:05 UTC, artsiombarouski requested changes

2019-08-08 12:05 UTC, artsiombarouski commented on bidmachine_android_mopub/src/main/java/com/mopub/mobileads/BidMachineUtils.java
> +        if (userId != null) {
Может быть должно быть `userId == null `

2019-08-08 12:11 UTC, NikitaCherep commented on bidmachine_android_mopub/src/main/java/com/mopub/mobileads/BidMachineUtils.java
> +        if (userId != null) {
Поправил

2019-08-09 08:43 UTC, artsiombarouski requested changes

2019-08-09 08:43 UTC, artsiombarouski commented on bidmachine_android_mopub/src/main/java/com/mopub/mobileads/BidMachineUtils.java
> +        if (userId == null) {
Поменять местами `userId` и `user_id`

2019-08-09 08:43 UTC, artsiombarouski commented on bidmachine_android_mopub/src/main/java/com/mopub/mobileads/BidMachineUtils.java
> +        if (priceFloors == null) {
Поменять местами `userId` и `user_id`

2019-08-09 08:45 UTC, artsiombarouski approved these changes

2019-08-09 09:21 UTC, merged